[package]
name = "component-test"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
futures-util = "0.3.33"
tokio = { version = "1.53.0", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
wac-graph = "0.10.1"
wasm-pkg-client = "0.16"
