[package]
name = "pm:lipl-server"
version = "0.1.2"
registry = "ghcr.io/paulusminus/pm/lipl-server"
kind = "component"
file = "build/lipl-server.wasm"
description = "A server for managing playlists and lyrics"
license = "MIT"
authors = ["Paul Min"]

[dependencies.components."pm:lipl-storage-fs"]
registry = "ghcr.io"
namespace = "paulusminus"
package = "pm/lipl-storage-fs"
version = "0.1.3"

[dependencies.interfaces."pm:lipl-core"]
registry = "ghcr.io"
namespace = "paulusminus"
package = "pm/lipl-core"
version = "0.3.2"
